### ISSUE TITLE
Verrazzano Operator install fails

### ISSUE THREAD

**Issue by mnemonic01** [verrazzano/verrazzano#1211]
Hi
The Operator fails to install, could you have a look at it?
I have a 3 node OKE Cluster ( K8s V1.19.7)

```
Applying kubectl apply -f https://github.com/verrazzano/verrazzano/releases/latest/download/operator.yaml

kubectl -n verrazzano-install rollout status deployment/verrazzano-platform-operator
```
This finally fails the pod with CrashLoopBackOff

Output from:
`kubectl --v=8 logs verrazzano-platform-operator-5f9f464bb4-fbz9s -n verrazzano-install`

```
I0603 09:58:01.379037   26953 loader.go:379] Config loaded from file:  /home/opc/.kube/config
I0603 09:58:01.384177   26953 round_trippers.go:422] GET https://152.70.162.109:6443/api/v1/namespaces/verrazzano-install/pods/verrazzano-platform-operator-5f9f464bb4-fbz9s
I0603 09:58:01.384204   26953 round_trippers.go:429] Request Headers:
I0603 09:58:01.384215   26953 round_trippers.go:433]     Accept: application/json, */*
I0603 09:58:01.384226   26953 round_trippers.go:433]     User-Agent: kubectl/v1.20.2 (linux/amd64) kubernetes/faecb19
I0603 09:58:08.558144   26953 round_trippers.go:448] Response Status: 200 OK in 7173 milliseconds
I0603 09:58:08.558181   26953 round_trippers.go:451] Response Headers:
I0603 09:58:08.558190   26953 round_trippers.go:454]     Cache-Control: no-cache, private
I0603 09:58:08.558201   26953 round_trippers.go:454]     Content-Type: application/json
I0603 09:58:08.558207   26953 round_trippers.go:454]     Date: Thu, 03 Jun 2021 09:58:08 GMT
I0603 09:58:08.558333   26953 request.go:1107] Response Body: {"kind":"Pod","apiVersion":"v1","metadata":{"name":"verrazzano-platform-operator-5f9f464bb4-fbz9s","generateName":"verrazzano-platform-operator-5f9f464bb4-","namespace":"verrazzano-install","selfLink":"/api/v1/namespaces/verrazzano-install/pods/verrazzano-platform-operator-5f9f464bb4-fbz9s","uid":"5d2b6e38-f346-4b40-be02-532cbccba5a7","resourceVersion":"316243","creationTimestamp":"2021-06-03T09:57:09Z","labels":{"app":"verrazzano-platform-operator","pod-template-hash":"5f9f464bb4"},"ownerReferences":[{"apiVersion":"apps/v1","kind":"ReplicaSet","name":"verrazzano-platform-operator-5f9f464bb4","uid":"54f844c2-9fa0-4fad-88ff-527dd3ecf13a","controller":true,"blockOwnerDeletion":true}],"managedFields":[{"manager":"kube-controller-manager","operation":"Update","apiVersion":"v1","time":"2021-06-03T09:57:09Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:generateName":{},"f:labels":{".":{},"f:app":{},"f:pod-template-hash":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"54f844c2-9fa0-4fad-88ff-527dd3ecf13a\"}":{ [truncated 6850 chars]
I0603 09:58:08.565698   26953 round_trippers.go:422] GET https://152.70.162.109:6443/api/v1/namespaces/verrazzano-install/pods/verrazzano-platform-operator-5f9f464bb4-fbz9s/log
I0603 09:58:08.565729   26953 round_trippers.go:429] Request Headers:
I0603 09:58:08.565741   26953 round_trippers.go:433]     Accept: application/json, */*
I0603 09:58:08.565751   26953 round_trippers.go:433]     User-Agent: kubectl/v1.20.2 (linux/amd64) kubernetes/faecb19
I0603 09:58:08.891262   26953 round_trippers.go:448] Response Status: 400 Bad Request in 325 milliseconds
I0603 09:58:08.891290   26953 round_trippers.go:451] Response Headers:
I0603 09:58:08.891308   26953 round_trippers.go:454]     Cache-Control: no-cache, private
I0603 09:58:08.891318   26953 round_trippers.go:454]     Content-Type: application/json
I0603 09:58:08.891323   26953 round_trippers.go:454]     Content-Length: 251
I0603 09:58:08.891328   26953 round_trippers.go:454]     Date: Thu, 03 Jun 2021 09:58:08 GMT
I0603 09:58:08.891356   26953 request.go:1107] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"container \"verrazzano-platform-operator\" in pod \"verrazzano-platform-operator-5f9f464bb4-fbz9s\" is waiting to start: PodInitializing","reason":"BadRequest","code":400}
I0603 09:58:08.891837   26953 helpers.go:216] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "container \"verrazzano-platform-operator\" in pod \"verrazzano-platform-operator-5f9f464bb4-fbz9s\" is waiting to start: PodInitializing",
  "reason": "BadRequest",
  "code": 400
}]
F0603 09:58:08.892242   26953 helpers.go:115] Error from server (BadRequest): container "verrazzano-platform-operator" in pod "verrazzano-platform-operator-5f9f464bb4-fbz9s" is waiting to start: PodInitializing
goroutine 1 [running]:
```

**Comment by mnemonic01** [comment]
I already found the reason
Within the webhook init container standard_init_linux.go:219: exec user process caused: exec format error appears because it probably expects AMD instead of my case ARM. Is verrazzano not yet certified to run on ARM?

**Comment by markxnelson** [comment]
Verrazzano is not tested or supported on ARM
