### ISSUE TITLE
Verrazzano Operator Version 1.2.1 install fails

### ISSUE THREAD

**Issue by ddevadat** [verrazzano/verrazzano#3054]
Hi
The Operator fails to install
I have a 2 node OKE Cluster ( K8s V1.22.5)

Command used:
`$ kubectl apply -f https://github.com/verrazzano/verrazzano/releases/download/v1.2.1/operator.yaml`

This finally fails the pod with CrashLoopBackOff

output logs from pod

```
[opc@v8o-operator ~]$ kubectl -n verrazzano-install --v=8 logs -f verrazzano-platform-operator-7c66d99678-z7zsz
I0503 16:51:57.762646  108891 loader.go:372] Config loaded from file:  /home/opc/.kube/config
I0503 16:51:57.772761  108891 round_trippers.go:463] GET https://10.0.0.22:6443/api/v1/namespaces/verrazzano-install/pods/verrazzano-platform-operator-7c66d99678-z7zsz
I0503 16:51:57.773036  108891 round_trippers.go:469] Request Headers:
I0503 16:51:57.773161  108891 round_trippers.go:473]     Accept: application/json, */*
I0503 16:51:57.773294  108891 round_trippers.go:473]     User-Agent: kubectl/v1.23.6 (linux/amd64) kubernetes/ad33385
I0503 16:52:01.445789  108891 round_trippers.go:574] Response Status: 200 OK in 3672 milliseconds
I0503 16:52:01.445817  108891 round_trippers.go:577] Response Headers:
I0503 16:52:01.445831  108891 round_trippers.go:580]     Cache-Control: no-cache, private
I0503 16:52:01.445841  108891 round_trippers.go:580]     Content-Type: application/json
I0503 16:52:01.445851  108891 round_trippers.go:580]     X-Kubernetes-Pf-Flowschema-Uid: 23568e4f-8240-4977-b6e9-0911b0db3470
I0503 16:52:01.445861  108891 round_trippers.go:580]     X-Kubernetes-Pf-Prioritylevel-Uid: 981d282b-efc6-43e3-8e82-b4045201a694
I0503 16:52:01.445870  108891 round_trippers.go:580]     Date: Tue, 03 May 2022 06:52:01 GMT
I0503 16:52:01.445881  108891 round_trippers.go:580]     Audit-Id: b6a56bf1-9495-40c1-a5a9-9998fd646de7
I0503 16:52:01.446053  108891 request.go:1181] Response Body: {"kind":"Pod","apiVersion":"v1","metadata":{"name":"verrazzano-platform-operator-7c66d99678-z7zsz","generateName":"verrazzano-platform-operator-7c66d99678-","namespace":"verrazzano-install","uid":"73ad5b2c-641e-4635-bbcd-1f1f9be9a37a","resourceVersion":"58672","creationTimestamp":"2022-05-03T06:47:00Z","labels":{"app":"verrazzano-platform-operator","pod-template-hash":"7c66d99678"},"ownerReferences":[{"apiVersion":"apps/v1","kind":"ReplicaSet","name":"verrazzano-platform-operator-7c66d99678","uid":"8c675e1f-61b9-4499-9426-b04e5092e3b1","controller":true,"blockOwnerDeletion":true}],"managedFields":[{"manager":"kube-controller-manager","operation":"Update","apiVersion":"v1","time":"2022-05-03T06:47:00Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:generateName":{},"f:labels":{".":{},"f:app":{},"f:pod-template-hash":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"8c675e1f-61b9-4499-9426-b04e5092e3b1\"}":{}}},"f:spec":{"f:containers":{"k:{\"name\":\"verrazzano-platform-operator\"}":{".":{},"f:args":{},"f:en [truncated 7111 chars]
I0503 16:52:01.449564  108891 round_trippers.go:463] GET https://10.0.0.22:6443/api/v1/namespaces/verrazzano-install/pods/verrazzano-platform-operator-7c66d99678-z7zsz/log?container=verrazzano-platform-operator&follow=true
I0503 16:52:01.449579  108891 round_trippers.go:469] Request Headers:
I0503 16:52:01.449592  108891 round_trippers.go:473]     Accept: application/json, */*
I0503 16:52:01.449604  108891 round_trippers.go:473]     User-Agent: kubectl/v1.23.6 (linux/amd64) kubernetes/ad33385
I0503 16:52:01.613300  108891 round_trippers.go:574] Response Status: 400 Bad Request in 163 milliseconds
I0503 16:52:01.613327  108891 round_trippers.go:577] Response Headers:
I0503 16:52:01.613336  108891 round_trippers.go:580]     Date: Tue, 03 May 2022 06:52:01 GMT
I0503 16:52:01.613341  108891 round_trippers.go:580]     Audit-Id: 85506cc9-949f-4f32-9cb1-3557d60ee73c
I0503 16:52:01.613347  108891 round_trippers.go:580]     Cache-Control: no-cache, private
I0503 16:52:01.613352  108891 round_trippers.go:580]     Content-Type: application/json
I0503 16:52:01.613359  108891 round_trippers.go:580]     Content-Length: 251
I0503 16:52:01.613389  108891 request.go:1181] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"container \"verrazzano-platform-operator\" in pod \"verrazzano-platform-operator-7c66d99678-z7zsz\" is waiting to start: PodInitializing","reason":"BadRequest","code":400}
I0503 16:52:01.613767  108891 helpers.go:219] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "container \"verrazzano-platform-operator\" in pod \"verrazzano-platform-operator-7c66d99678-z7zsz\" is waiting to start: PodInitializing",
  "reason": "BadRequest",
  "code": 400
}]
F0503 16:52:01.613805  108891 helpers.go:118] Error from server (BadRequest): container "verrazzano-platform-operator" in pod "verrazzano-platform-operator-7c66d99678-z7zsz" is waiting to start: PodInitializing
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0x1)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1038 +0x8a
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x3080040, 0x3, 0x0, 0xc00003a7e0, 0x2, {0x25f2ec7, 0x10}, 0xc000454800, 0x0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:987 +0x5fd
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printDepth(0xc0000b4580, 0xa4, 0x0, {0x0, 0x0}, 0xc000012008, {0xc00058faf0, 0x1, 0x1})
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:735 +0x1ae
k8s.io/kubernetes/vendor/k8s.io/klog/v2.FatalDepth(...)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1518
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.fatal({0xc0000b4580, 0xa4}, 0xc0007fb220)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:96 +0xc5
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.checkErr({0x1feb840, 0xc0007fb220}, 0x1e797d0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:191 +0x7d7
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.CheckErr(...)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:118
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/logs.NewCmdLogs.func1(0xc0003bc000, {0xc000496320, 0x1, 0x5})
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/logs/logs.go:159 +0x125
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc0003bc000, {0xc000498780, 0x5, 0x6})
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:860 +0x5f8
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000657680)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:974 +0x3bc
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:902
k8s.io/kubernetes/vendor/k8s.io/component-base/cli.run(0xc000657680)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/cli/run.go:146 +0x325
k8s.io/kubernetes/vendor/k8s.io/component-base/cli.RunNoErrOutput(...)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/cli/run.go:84
main.main()
        _output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:30 +0x1e

goroutine 6 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1181 +0x6a
created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:420 +0xfb

goroutine 17 [select]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0, {0x1febb40, 0xc000597dd0}, 0x1, 0xc00004a3c0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x13b
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x12a05f200, 0x0, 0x0, 0x0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Forever(0x0, 0x0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:81 +0x28
created by k8s.io/kubernetes/vendor/k8s.io/component-base/logs.InitLogs
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/logs/logs.go:179 +0x85

goroutine 80 [IO wait]:
internal/poll.runtime_pollWait(0x7f0d077ce9d8, 0x72)
        /usr/local/go/src/runtime/netpoll.go:303 +0x85
internal/poll.(*pollDesc).wait(0xc000680100, 0xc000922000, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000680100, {0xc000922000, 0x2074, 0x2074})
        /usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc000680100, {0xc000922000, 0x73, 0xc00087c920})
        /usr/local/go/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc000460000, {0xc000922000, 0xc000923ffc, 0x5})
        /usr/local/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc0007ce270, {0xc000922000, 0x0, 0x409e2d})
        /usr/local/go/src/crypto/tls/conn.go:777 +0x3d
bytes.(*Buffer).ReadFrom(0xc0005845f8, {0x1fe9980, 0xc0007ce270})
        /usr/local/go/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc000584380, {0x7f0d075f8100, 0xc0009042b8}, 0x78)
        /usr/local/go/src/crypto/tls/conn.go:799 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc000584380, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:606 +0x112
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:574
crypto/tls.(*Conn).Read(0xc000584380, {0xc000897000, 0x1000, 0x8da880})
        /usr/local/go/src/crypto/tls/conn.go:1277 +0x16f
bufio.(*Reader).Read(0xc000499e60, {0xc000120740, 0x9, 0x8e8842})
        /usr/local/go/src/bufio/bufio.go:227 +0x1b4
io.ReadAtLeast({0x1fe9780, 0xc000499e60}, {0xc000120740, 0x9, 0x9}, 0x9)
        /usr/local/go/src/io/io.go:328 +0x9a
io.ReadFull(...)
        /usr/local/go/src/io/io.go:347
k8s.io/kubernetes/vendor/golang.org/x/net/http2.readFrameHeader({0xc000120740, 0x9, 0xc0014d5980}, {0x1fe9780, 0xc000499e60})
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/frame.go:237 +0x6e
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc000120700)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/frame.go:498 +0x95
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*clientConnReadLoop).run(0xc0004cbf98)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:2101 +0x130
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*ClientConn).readLoop(0xc000468300)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:1997 +0x6f
created by k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Transport).newClientConn
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:725 +0xac5

goroutine 84 [IO wait]:
internal/poll.runtime_pollWait(0x7f0d077ce8e8, 0x72)
        /usr/local/go/src/runtime/netpoll.go:303 +0x85
internal/poll.(*pollDesc).wait(0xc000681800, 0xc000103000, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000681800, {0xc000103000, 0xaf9, 0xaf9})
        /usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc000681800, {0xc000103000, 0xa7a, 0xc00087cac0})
        /usr/local/go/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc000460030, {0xc000103000, 0xc00010307a, 0x5})
        /usr/local/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc000412618, {0xc000103000, 0x0, 0x409e2d})
        /usr/local/go/src/crypto/tls/conn.go:777 +0x3d
bytes.(*Buffer).ReadFrom(0xc000584978, {0x1fe9980, 0xc000412618})
        /usr/local/go/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc000584700, {0x7f0d075f8100, 0xc0009044e0}, 0xa7f)
        /usr/local/go/src/crypto/tls/conn.go:799 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc000584700, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:606 +0x112
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:574
crypto/tls.(*Conn).Read(0xc000584700, {0xc0008ab000, 0x1000, 0x8da880})
        /usr/local/go/src/crypto/tls/conn.go:1277 +0x16f
bufio.(*Reader).Read(0xc0002652c0, {0xc0001209e0, 0x9, 0x8e8842})
        /usr/local/go/src/bufio/bufio.go:227 +0x1b4
io.ReadAtLeast({0x1fe9780, 0xc0002652c0}, {0xc0001209e0, 0x9, 0x9}, 0x9)
        /usr/local/go/src/io/io.go:328 +0x9a
io.ReadFull(...)
        /usr/local/go/src/io/io.go:347
k8s.io/kubernetes/vendor/golang.org/x/net/http2.readFrameHeader({0xc0001209e0, 0x9, 0xc00197a0c0}, {0x1fe9780, 0xc0002652c0})
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/frame.go:237 +0x6e
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc0001209a0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/frame.go:498 +0x95
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*clientConnReadLoop).run(0xc000913f98)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:2101 +0x130
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*ClientConn).readLoop(0xc000468a80)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:1997 +0x6f
created by k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Transport).newClientConn
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:725 +0xac5
```

**Comment by ddevadat** [comment]
issue was with the kubernetes version v1.22.5 which is unsupported

**Comment by shihchang** [comment]
https://verrazzano.io/v1.2/docs/setup/prereqs/  - Verrazzano v1.2.1 supports Kubernetes 1.19, 1.20, 1.21; it does not have 1.22. For OKE, verified it is working on v1.21.5.
